### ISSUE TITLE
[TASK] Connect Travis CI to repository & write basic test case

### ISSUE THREAD

**Issue by anonna16** [QuangTran304/Instagram-Clone#33]
**Story Points**: 1
**Priority**: High

**Comment by QuangTran304** [comment]
Just switched our Repo from Private to be Public since Travis CI stated that they'll be FREE for Open Source Projects.

Also, I added a config file for Travis CI, feel free to edit it.

<img width="1181" alt="Screen Shot 2021-02-09 at 12 19 57 PM" src="https://user-images.githubusercontent.com/45047536/107401838-439cf100-6ad1-11eb-8a70-a2de46e71550.png">

**Comment by QuangTran304** [comment]
Task done!
